# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kandidat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipilih', to='kandidat.Kandidat')),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
