# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilih', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilih',
            options={'permissions': (('bisa_vote', 'Pemilih bisa melakukan vote'),)},
        ),
    ]
