# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilih', '0003_pilih_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilih',
            name='pemilih',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to=settings.AUTH_USER_MODEL),
        ),
    ]
