# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilih', '0004_auto_20180220_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilih',
            name='kandidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dipilih', to='kandidat.Kandidat'),
        ),
        migrations.AlterField(
            model_name='pilih',
            name='pemilih',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to=settings.AUTH_USER_MODEL),
        ),
    ]
