# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilih', '0005_auto_20180221_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilih',
            name='kandidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipilih', to='kandidat.Kandidat'),
        ),
    ]
