# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilih', '0006_auto_20180221_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilih',
            name='pemilih',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to='pemilih.Pemilih'),
        ),
    ]
