# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemilih', '0002_remove_pemilih_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='cetak',
            field=models.BooleanField(default=False),
        ),
    ]
